--Caso nao seja Oracle o Banco de dados, talvez tera de criar o banco antes.
--Neste caso utilize o comando: Create Database Biblioteca;
--Aqui sera aplicado conhecimentos em DQL DML e DDL.

CREATE TABLE Livros(

ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
titulo VARCHAR2 (300) NOT NULL,
autor VARCHAR2 (300) NOT NULL,
editora VARCHAR2 (200)NOT NULL,
ano_publicacao INT
);

CREATE TABLE Usuarios (
id number generated by default as identity primary key,
nome VARCHAR2 (300) NOT NULL,
cpf CHAR (11) NOT NULL,
endereco VARCHAR2 (300),
telefone CHAR (10),
celular CHAR (13) NOT NULL,
email VARCHAR2 (250)
);

CREATE TABLE Emprestimos (
id int generated always as identity primary key,
id_livro INT,
id_usuario INT,
data_emprestimo DATE NOT NULL,
data_devolucao DATE NOT NULL,
FOREIGN KEY (id_livro) REFERENCES Livros(id),
FOREIGN KEY (id_usuario) REFERENCES Usuarios(id)
);



INSERT INTO Livros (titulo, autor, editora, ano_publicacao) VALUES
('Os Vestígios do dia', 'Kazuo Ishiguro', 'Companhia das Letras', '2016');

INSERT INTO Livros (titulo, autor, editora, ano_publicacao) VALUES
('21 lições para o século 21', 'Yuval Noah Harari', 'Companhia das Letras', '2018');

INSERT INTO Livros (titulo, autor, editora, ano_publicacao) VALUES
('Homo Deus', 'Yuval Noah Harari', 'Companhia das Letras', '2016');

INSERT INTO Livros (titulo, autor, editora, ano_publicacao) VALUES
('Competindo Contra O Tempo', 'George Stalk Jr Thomas M Hout', 'Record', '1993');

INSERT INTO Livros (titulo, autor, editora, ano_publicacao) VALUES
('Snow Crash', 'Neal Stephenon', 'Editora Aleph', '2015');

INSERT INTO Livros (titulo, autor, editora, ano_publicacao) VALUES
('Neuromancer', 'William Gibson', 'Editora Aleph', '2016');

INSERT INTO Livros (titulo, autor, editora, ano_publicacao) VALUES
('Just For Fun The Story of an Accidental Revolutionary', 'Linus Torvalds e David Diamond', 'HarperBusiness', '2002');

INSERT INTO Livros (titulo, autor, editora, ano_publicacao) VALUES
('Hackers Heroes of the Computer Revolution', 'Steven Levy', 'O Reilly Media', '2010');

INSERT INTO Livros (titulo, autor, editora, ano_publicacao) VALUES
('Expert Oracle Database Architecture', 'Thomas Kyte e Darl Kuhn', 'Apress', '2014'); 

COMMIT;

INSERT INTO Usuarios (nome, cpf, endereco, telefone, celular, email) VALUES
('Steve Jobs', '14758236945', 'Wall Street 45 Nova Iorque', '1145825846', '0155914589852', 'steve.j@hotmail.com');

INSERT INTO Usuarios (nome, cpf, endereco, telefone, celular, email) VALUES
('Steve Wozniak', '54812567841', 'Orchard Road 515 Singapura', '1445853266', '0135955145589', 'wozniak@gmail.com');

INSERT INTO Usuarios (nome, cpf, endereco, telefone, celular, email) VALUES
('Ronald Wayne', '14785269551', 'La Rambla 22 Barcelona', '1145259877', '0122958451128', 'ronald_wayne@hotmail.com');

INSERT INTO Usuarios (nome, cpf, endereco, telefone, celular, email) VALUES
('Lauren Sanc', '14587122584', 'Boulevard Street 16 Hollywood', '1522458891', '22139458892', 'lauren_sn@gmail.com');

INSERT INTO Usuarios (nome, cpf, endereco, telefone, celular, email) VALUES
('Sergey Brin', '13582221334', 'Vine Street 35 Hollywood', '3522159899', '1488914589874', 'sergey@hotmail.com');

INSERT INTO Usuarios (nome, cpf, endereco, telefone, celular, email) VALUES
('Bill Gates', '95247122985', 'Lombard Street 11 San Franscico', '8914772815', '0455998254136', 'biil_gates@hotmail.com');

INSERT INTO Usuarios (nome, cpf, endereco, telefone, celular, email) VALUES
('Paul Allen', '78954321687', 'Pollocks Path The Peak 55 Hong Kong', '7855224171', '0239988154716', 'paulallen@gmai.com');

INSERT INTO Usuarios (nome, cpf, endereco, telefone, celular, email) VALUES
('Larry Ellison', '89542369847', 'Fifth Avenue 100 Nova York', '3456987414', '0816985472200', 'larry.elisson@hotmail.com');

INSERT INTO Usuarios (nome, cpf, endereco, telefone, celular, email) VALUES
('Mack Scott', '88965321457', 'Abbey Road 1200 Londres', '2151512897', '7722945669191', 'mack_scoot@gmail.com');

COMMIT;

SELECT*FROM usuarios;

INSERT INTO Emprestimos (id_livro, id_usuario, data_emprestimo, data_devolucao) VALUES
(1, 2, '05-10-2022', '25-06-2022');

INSERT INTO emprestimos (id_livro, id_usuario, data_emprestimo, data_devolucao) VALUES
(2, 5, '05-04-2023', '20-04-2023');

INSERT INTO emprestimos (id_livro, id_usuario, data_emprestimo, data_devolucao) VALUES
(3, 3, '06-02-2020', '21-02-2020');

INSERT INTO emprestimos (id_livro, id_usuario, data_emprestimo, data_devolucao) VALUES
(9, 1, '04-03-2022', '24-03-2022');

INSERT INTO emprestimos (id_livro, id_usuario, data_emprestimo, data_devolucao) VALUES
(5, 9, '08-11-2021', '21-12-2021');

INSERT INTO emprestimos (id_livro, id_usuario, data_emprestimo, data_devolucao) VALUES
(7, 8, '20-06-2022', '07-02-2021');

INSERT INTO emprestimos (id_livro, id_usuario, data_emprestimo, data_devolucao) VALUES
(4, 4, '21-12-2021', '22-03-2022');

INSERT INTO emprestimos (id_livro, id_usuario, data_emprestimo, data_devolucao) VALUES
(8, 6, '17-01-2023', '01-03-2023');

INSERT INTO emprestimos (id_livro, id_usuario, data_emprestimo, data_devolucao) VALUES
(6, 7, '27-08-2020', '28-01-2021');

COMMIT;



--Último testa para saber se tudo deu certo--

SELECT Livros.titulo, Emprestimos.id_livro, Emprestimos.id_usuario, Emprestimos.data_emprestimo, Emprestimos.data_devolucao, Usuarios.nome
FROM Livros
FULL OUTER JOIN Emprestimos
ON Livros.id = Emprestimos.id_livro
FULL OUTER JOIN Usuarios
ON Emprestimos.id_usuario = Usuarios.id;
